name = "rudl-dl-v2"
compatibility_date = "2025-10-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# Additional worker variables can be defined here.

[[d1_databases]]
binding = "DB"
database_name = "rudl_app"
database_id = "6971cadc-b4f7-4642-bc78-f1e5e1bee999"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "mycowbay-files"

